spring:
  application:
    name: EMall
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 112233
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis配置
mybatis:
  mapper-locations: classpath:org/example/mall/mbg/mapper/*.xml
  type-aliases-package: org.example.mall.mbg.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# SpringDoc OpenAPI 配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: org.example.mall.controller
  paths-to-match: /api/**

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /
    
# 日志配置
logging:
  level:
    '[org.example.mall]': debug
    '[org.springframework.web]': debug
    '[org.mybatis]': debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
