package org.example.mall.mbg.model;

import java.io.Serializable;
import java.util.Date;

/**
 * ums_member 表对应的实体类
 * 会员信息表
 *
 * @author MyBatis Generator
 */
public class UmsMember implements Serializable {
    /**
     * 会员ID，主键
     */
    private Long id;

    /**
     * 会员用户名
     */
    private String username;

    /**
     * 会员密码（加密存储）
     */
    private String password;

    /**
     * 会员昵称
     */
    private String nickname;

    /**
     * 会员手机号
     */
    private String phone;

    /**
     * 会员邮箱
     */
    private String email;

    /**
     * 会员状态：0->禁用；1->启用
     */
    private Boolean status;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新时间
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_member
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取会员ID，主键
     *
     * @return id 会员ID，主键
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置会员ID，主键
     *
     * @param id 会员ID，主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取会员用户名
     *
     * @return username 会员用户名
     */
    public String getUsername() {
        return username;
    }

    /**
     * 设置会员用户名
     *
     * @param username 会员用户名
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * 获取会员密码（加密存储）
     *
     * @return password 会员密码（加密存储）
     */
    public String getPassword() {
        return password;
    }

    /**
     * 设置会员密码（加密存储）
     *
     * @param password 会员密码（加密存储）
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * 获取会员昵称
     *
     * @return nickname 会员昵称
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * 设置会员昵称
     *
     * @param nickname 会员昵称
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * 获取会员手机号
     *
     * @return phone 会员手机号
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 设置会员手机号
     *
     * @param phone 会员手机号
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * 获取会员邮箱
     *
     * @return email 会员邮箱
     */
    public String getEmail() {
        return email;
    }

    /**
     * 设置会员邮箱
     *
     * @param email 会员邮箱
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * 获取会员状态：0->禁用；1->启用
     *
     * @return status 会员状态：0->禁用；1->启用
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * 设置会员状态：0->禁用；1->启用
     *
     * @param status 会员状态：0->禁用；1->启用
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * 获取创建时间
     *
     * @return create_time 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置创建时间
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取更新时间
     *
     * @return update_time 更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置更新时间
     *
     * @param updateTime 更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", nickname=").append(nickname);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}