package org.example.mall.mbg.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.mall.mbg.model.PmsProduct;
import org.example.mall.mbg.model.PmsProductExample;

public interface PmsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     */
    long countByExample(PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     */
    int deleteByExample(PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     */
    int insert(PmsProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     */
    int insertSelective(PmsProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     */
    List<PmsProduct> selectByExample(PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     */
    PmsProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     */
    int updateByExampleSelective(@Param("row") PmsProduct row, @Param("example") PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     */
    int updateByExample(@Param("row") PmsProduct row, @Param("example") PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     */
    int updateByPrimaryKeySelective(PmsProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     */
    int updateByPrimaryKey(PmsProduct row);
}