package org.example.mall.mbg.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.mall.mbg.model.UmsMember;
import org.example.mall.mbg.model.UmsMemberExample;

public interface UmsMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     */
    long countByExample(UmsMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     */
    int deleteByExample(UmsMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     */
    int insert(UmsMember row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     */
    int insertSelective(UmsMember row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     */
    List<UmsMember> selectByExample(UmsMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     */
    UmsMember selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     */
    int updateByExampleSelective(@Param("row") UmsMember row, @Param("example") UmsMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     */
    int updateByExample(@Param("row") UmsMember row, @Param("example") UmsMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     */
    int updateByPrimaryKeySelective(UmsMember row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_member
     */
    int updateByPrimaryKey(UmsMember row);
}